### ISSUE TITLE
Check for `.readthedocs.yml` existence

### ISSUE THREAD

**Issue by Raruto** [g3w-suite/g3w-suite-documentation#6]
I don't know if this file is actually needed to deploy on readthedocs.com (maybe just to run this locally?). But, at a quick glance, it seems that it hasn't been included in this repository (ref: https://github.com/g3w-suite/g3w-admin/pull/440)

```yml

# g3w-admin@v3.5/.readthedocs.yml

version: 2
formats: all
sphinx:
  configuration: docs/conf.py
python:
   version: 3.7
   install:
      - requirements: docs/requirements.txt
```
